version: '3.8'

services:

  apm-server:
    image: docker.elastic.co/apm/apm-server:7.15.0
    cap_add: ["CHOWN", "DAC_OVERRIDE", "SETGID", "SETUID"]
    cap_drop: ["ALL"]
    ports:
     - 8200:8200
    environment:
      - ELASTICSEARCH_URL=http://host.docker.internal:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
      - setup.kibana.host=host.docker.internal:5601
      - setup.template.settings.index.number_of_replicas=0
    networks:
      - elastic
    volumes:
      - ./apm-server-config.yml:/usr/share/apm-server/apm-server.yml:ro
  
  elasticsearch:
   container_name: elasticsearch
   image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
   ports:
    - 9200:9200
   volumes:
    - elasticsearch-data:/usr/share/elasticsearch/data
   networks:
    - elastic
   environment:
    - xpack.monitoring.enabled=true
    - xpack.watcher.enabled=false
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - discovery.type=single-node      
    - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    - bootstrap.memory_lock=true
    - xpack.security.enabled=false
    - xpack.security.http.ssl.enabled=false
    - xpack.security.transport.ssl.enabled=false
    - xpack.license.self_generated.type=${LICENSE}
    - xpack.security.authc.token.enabled=false
   extra_hosts:
     - "host.docker.internal:host-gateway"

  kibana:
   container_name: kibana
   image: docker.elastic.co/kibana/kibana:7.15.0
   ports:
    - 5601:5601
   depends_on:
    - elasticsearch
   networks:
    - elastic
   environment:
    - ELASTICSEARCH_URL=http://host.docker.internal:9200
    - xpack.apm.enabled=false    
    - ELASTICSEARCH_USERNAME=elastic
    - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    - xpack.security.audit.enabled=true
    - xpack.security.enabled=false
    - xpack.security.disabled=true
    - xpack.security.anonymous.enable=true
   extra_hosts:
     - "host.docker.internal:host-gateway"

  otel-collector:
   image: otel/opentelemetry-collector:0.76.1
   command: [--config=/etc/otel-collector-config.yaml]
   volumes:
     - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
   networks:
      - elastic
   extra_hosts:
     - "host.docker.internal:host-gateway"
   ports:
     - 1888:1888 # pprof extension
     - 8888:8888 # Prometheus metrics exposed by the collector
     - 8889:8889 # Prometheus exporter metrics
     - 13133:13133 # health_check extension
     - 4315:4315 # OTLP gRPC receiver
     - 4318:4318 # OTLP http receiver
     - 55679:55679 # zpages extension

  app-input-data:
    build: ./ProjectInputData/
    environment:
      - ASPNETCORE_URLS=http://app-input-data:80
    ports:
      - 5001:80
    networks:
      - elastic
    extra_hosts:
      - "host.docker.internal:host-gateway"

  
networks:
  elastic:
    driver: bridge

volumes:
  elasticsearch-data:


  # TODO: 
  # create api key in apm server
  # apm server connection elastic search falta user and senha conig no elastic e no apm para acessar ele 
  # apm-server apikey create --ingest --agent-config --name java-001 -E output.elasticsearch.username=elastic -E output.elasticsearch.password=pass@123 --json