receivers: 
  # ...
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4315
      http:
        endpoint: 0.0.0.0:4318


processors: 
  # ...
  memory_limiter:
    check_interval: 1s
    limit_mib: 512
  batch:

exporters:
  logging:
    verbosity: detailed

  otlp/elastic: 
    # Elastic APM server https endpoint without the "https://" prefix
    endpoint: "apm-server:8200"  
    tls:
      insecure: true
    compression: none 
    #headers:
      # Elastic APM Server secret token
      #Authorization: "Bearer ca50d01e-b207-4066-adb2-d01adaf9ab77"  

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlp/elastic]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlp/elastic]
    logs: 
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlp/elastic]