receivers: 
  # ...
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318


processors: 
  # ...
  memory_limiter:
    check_interval: 1s
    limit_mib: 512
  batch:

exporters:
  logging:

  otlphttp: 
    # Elastic APM server https endpoint without the "https://" prefix
    endpoint: "http://host.docker.internal:8200"  
    tls:
      insecure: true
    headers:
      # Elastic APM Server secret token
      Authorization: "Bearer ca50d01e-b207-4066-adb2-d01adaf9ab77"  

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlphttp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlphttp]
    logs: 
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlphttp]